rootProject.name = "jimmer"
include("jimmer-core")
include("jimmer-mapstruct-apt")
include("jimmer-apt")
include("jimmer-sql")
include("jimmer-core-kotlin")
include("jimmer-ksp")
include("jimmer-sql-kotlin")
include("jimmer-client")
include("jimmer-spring-boot-starter")
include("jimmer-dto-compiler")
include("jimmer-client-swagger")
include("jimmer-quarkus")
include("jimmer-quarkus:runtime")
include("jimmer-quarkus:deployment")
include("jimmer-quarkus:integration-tests")