package org.babyfish.jimmer;

/**
 * <p>
 *     Lambda expressions for modifying mutable draft.
 * </p>
 *
 * <p>
 *     Similar to {@code java.util.function.Consumer}, but allows exceptions to be thrown.
 * </p>
 * @param <D> The draft interface generated by Annotation Processor.
 */
@FunctionalInterface
public interface DraftConsumer<D> {

    void accept(D draft) throws Throwable;
}
