package org.babyfish.jimmer;

/**
 * The mutable interface generated by the Annotation processor inherits this interface,
 * and the user interface should not inherit this interface.
 */
public interface Draft {}
