package org.babyfish.jimmer;

/**
 * Super interface for static input DTO classes generated by Jimmer.
 *
 * Note, this interface should only be implemented by
 * generated code, not developer
 *
 * @param <E> The dynamic entity interface type
 */
public interface Input<E> extends Static<E> {
}
