package org.babyfish.jimmer;

/**
 * Super interface for static DTO classes generated by
 * the annotation @{@link org.babyfish.jimmer.pojo.StaticType}
 * when the `topLevelName` of @{@link org.babyfish.jimmer.pojo.StaticType}
 * ends with `Input`.
 *
 * Note, this interface should only be implemented by
 * generated code, not developer
 *
 * @param <E> The dynamic entity interface type
 */
public interface Input<E> extends Static<E> {
}
