package org.babyfish.jimmer;

import org.jetbrains.annotations.NotNull;

/**
 * Super interface for static DTO classes generated by
 * the annotation @{@link org.babyfish.jimmer.pojo.StaticType}
 *
 * Note, this interface should only be implemented by
 * generated code, not developer
 *
 * @param <E> The dynamic entity interface type
 */
public interface Static<E> {

    @NotNull
    E toEntity();

    @NotNull
    E toEntity(E base);
}
