package org.babyfish.jimmer.sql.filter;

import org.babyfish.jimmer.sql.ast.table.Props;
import org.babyfish.jimmer.sql.event.EntityEvent;

import java.util.SortedMap;

/**
 * Global filter for java, Kotlin developer should use `KFilter&lt;E&gt;`
 * @param <P> The EntityProps type generated by apt
 */
public interface Filter<P extends Props> {

    void filter(FilterArgs<P> args);
}
