package org.babyfish.jimmer.sql.filter;

import org.babyfish.jimmer.sql.ast.table.Props;

/**
 * Sharding global filter for java, Kotlin developer should use `KShardingFilter&lt;E&gt;`
 *
 * <p>Sharding filter means the filter conditions will always be used, even if when query object(s) by id(s).</p>
 *
 * @param <P> The EntityProps type generated by apt
 */
public interface ShardingFilter<P extends Props> extends Filter<P> {
}
